### ISSUE TITLE
certificates created with GnuTLS not functioning anymore

### ISSUE THREAD

**Issue by debalance** [processone/pkix#2]
Hi, in https://bugs.debian.org/933040 somebody reports that certificates created with GnuTLS are no longer compatible with ejabberd. It has been working at least up to 16.09, but does not with 18.12.1.

The problem can be reduced like this on a fresh Debian 10 "Buster" installation:

  1. apt install ejabberd (debconf questions won't matter)

  2. copy the four attached certs/keys to /etc/ejabberd (remove the .txt at the end)

  3. edit ejabberd.yml with:

       hosts:
         - "jabber.example.com"

       certfiles:
          - "/etc/ejabberd/ejabberd-cert.pem"
          - "/etc/ejabberd/ejabberd-key.pem"
          - "/etc/ejabberd/private-int-cert.pem"
          - "/etc/ejabberd/private-ca-cert.pem"

   4. systemctl restart ejabberd

   5. examine output of the following commands:

        gnutls-cli -V --x509cafile=/etc/ejabberd/private-ca-cert.pem --verify --hostname=jabber.example.com -p 5223 localhost:5223 < /dev/null

       certtool --certificate-info --load-certificate /etc/ejabberd/ejabberd-cert.pem

The gnutls-cli command reports:

  Status: The certificate is NOT trusted. The signature in the
  certificate is invalid.

Earlier in the gnutls-cli output is the signature received on the wire:

  sha1:647fe53a3b279f605d2ec7a572c54724f0765285

The certtool command shows a different signature:

  sha1:9789b39f3b5bde6a8c5b7dd2c11c25c901199edf

So somehow ejabberd seems to be recomputing the signature when it should match what's in the PEM file verbatim.

[ejabberd-cert.pem.txt](https://github.com/processone/pkix/files/3437247/ejabberd-cert.pem.txt)
[ejabberd-key.pem.txt](https://github.com/processone/pkix/files/3437248/ejabberd-key.pem.txt)
[private-ca-cert.pem.txt](https://github.com/processone/pkix/files/3437249/private-ca-cert.pem.txt)
[private-int-cert.pem.txt](https://github.com/processone/pkix/files/3437250/private-int-cert.pem.txt)

**Comment by debalance** [comment]
FWIW, Debian 10 "Buster" ships Erlang 21.2.6.
I was able to reproduce the problem on Debian 9 "Stretch" as well (also with ejabberd 18.12.1, from stretch-backports), which ships Erlang 19.2.1.

**Comment by zinid** [comment]
Note however, that `dumpasn1` (version 20170309-1 from Debian) reports the following:
```
$ dumpasn1 /tmp/orig.der
...
 772   15:         SEQUENCE {
 774    3:           OBJECT IDENTIFIER keyUsage (2 5 29 15)
 779    1:           BOOLEAN TRUE
 782    5:           OCTET STRING, encapsulates {
 784    3:             BIT STRING 7 unused bits
         :               '000100000'B (bit 5)
         :               Error: Spurious zero bits in bitstring.
         :             }
         :           }
...
0 warnings, 1 error.
```
So I would not rule out GnuTLS ASN.1 encoder bug.
